version: '3.8'

services:
  # Flask Backend Server
  backend:
    build: ./docuMind_server
    container_name: documind-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
      - APPWRITE_BUCKET_ID=${APPWRITE_BUCKET_ID}
    volumes:
      - ./docuMind_server:/app
    restart: unless-stopped

  # React Frontend Client
  frontend:
    build: ./docuMind_client
    container_name: documind-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./docuMind_client:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped